# FROM ubuntu:22.04
# RUN apt-get update
# RUN apt-get install -y nginx
# ADD . /var/www/html
# EXPOSE 80

FROM node:14-alpine
# RUN apt-get update
# RUN apt-get install -y nodejs
# RUN apt-get install -y npm
# RUN npm install tar@6 -g
# RUN node -v
# # RUN npm install tar@latest
# RUN npm install create-react-app
# RUN create-react-app mi-primera-app
# RUN npm start
